### ISSUE TITLE
use lingascript to compile vscode_english_chinese_dictionary

### ISSUE THREAD

**Issue by gasolin** [gasolin/lingascript#9]
Try to compile https://github.com/program-in-chinese/vscode_english_chinese_dictionary with lingascript.

Note currently lingascript does not provide the pre-build version yet. You need build first and run with command like

```
node typescript/built/local/tsc.js -p vscode_english_chinese_dictionary
```

@testacount1 @nobodxbodon are you interest in this?

**Comment by nobodxbodon** [comment]
To make sure, is the purpose to test lingascript in real typescript projects? It might add some extra complexity as it's a vscode extension. I mainly relied on vscode's built-in support to build and used vsce to publish, instead of directly using tsc compiler during development.
I wonder if a more 'typical' typescript project would be better as candidate for testing?

**Comment by gasolin** [comment]
thanks for giving the feedback of how to build vscode_english_chinese_dictionary
yes it sounds not a good candidate to test lingascript in real typescript projects, close this issue
